---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: simple-app
  namespace: iris-green
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/warroyo/iris-green-app

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: simple-app
  namespace: iris-green
spec:
  interval: 10m0s
  path: ./config/k8s/dev
  prune: true
  serviceAccountName: tenant-flux-reconciler
  targetNamespace: iris-green-apps
  sourceRef:
    kind: GitRepository
    name: simple-app